# docker-compose.yml
version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=data@123
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql  # Data survives container restarts
volumes:
  sqlserver-data:
